Fix log4j dep issues
org.apache.log4j.Logger was not importing correctly.
Modified pom files to allow reload4j as a dependency to fix Logger
import errors.
Added Tserver groups to balancer

With the switch to accumulo 4.0, tservers are now assigned a resource
group on startup. This group information is now passed to the balancer
to assist with tserver specific balancer decisions.
Attempt to work through in-memory-accumulo issues

Tried to build against accumulo 4.0.0-SNAPSHOT. Found errors with
InMemoryAccumulo. Attempted to resolve them by adding a instanceID
method to InMemoryAccumulo and swapping it for all missing instances of
InMemoryInstance.

Ran into errors with not having push access to submodule
datawave-in-memory-accumulo.

Think it might be less effort to create a cachingScanner vs continue
using the in-memory accumulo instance.
Next Set of compiler fixes
update BulkInputFormat to use TabletInformation APIs
use new iterator env config methods
fix ConfigurableIteratorEnvironment
fix TableSplitsCache
got BulkIngestMapFileLoader.java to compile, but its a hack
Fix accumulo4 related test failures

* fix AggregatingReducer.java
* fix MultiRFileOutputFormatter usage of internal rfile APIs
* fix MetricsTableConfigHelperTest.java
* fix NumShardsTest.java
* fix PropogatingIteratorTest.java
* fix TableConfigHelperFactoryTest.java
* fix multiple in mem accumulo related compile errors
* fix multiple in mem accumulo related compile errors
* fix up usages of TabletLocator
* fix compile errors in query module
* remove handling for relative paths in Accumulo
* fix compile error in QueryIterator w/ hack
* remove Connector usage from ScannerFactory
* automaticly replace InMemoryInstance

ran the following commands to create this commit

```
cd warehouse/query-core/src/test
find -name "*.java" | xargs sed -i -e 's/InMemoryInstance/InMemoryAccumulo/g'
```
fix compile errors in QueryIteratorIT and SourceManagerTest
automatically replace more InMemoryInstance

```
 cd web-services/map-reduce/src/test
 find -name "*.java" | xargs sed -i -e 's/InMemoryInstance/InMemoryAccumulo/g'
```

```
 cd datawave/web-services/model/src/test
 find -name "*.java" | xargs sed -i -e 's/InMemoryInstance/InMemoryAccumulo/g'
```
update metrics-core to use new Accumulo mapreduce API
Updated iterator config code
pom updates needed to get some test to run
remove reload4j from classpath as it was causing test failures

Was seeing test failure like the following.  Seemed related to having
reload4j on the classpath. Removed it from classpath, do not think it is
needed becasue there is already something providing runtime support for
log4j1.

```
[INFO] ---------------< gov.nsa.datawave:datawave-ingest-core >----------------
[INFO] Building datawave-ingest-core 7.7.0-SNAPSHOT                    [19/116]
[INFO] --------------------------------[ jar ]---------------------------------

[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.099 s -- in datawave.ingest.data.normalizer.SimpleGroupFieldNameParserTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.278 s <<< FAILURE! -- in datawave.util.flag.InputFileTest
[ERROR] datawave.util.flag.InputFileTest.testUpdateDir -- Time elapsed: 0.258 s <<< ERROR!
java.lang.NoSuchMethodError: 'org.apache.logging.log4j.Level org.apache.log4j.helpers.OptionConverter.convertLevel(java.lang.String, org.apache.logging.log4j.Level)'
	at org.apache.log4j.config.PropertiesConfiguration.parseLogger(PropertiesConfiguration.java:416)
	at org.apache.log4j.config.PropertiesConfiguration.configureRoot(PropertiesConfiguration.java:349)
	at org.apache.log4j.config.PropertiesConfiguration.doConfigure(PropertiesConfiguration.java:326)
	at org.apache.log4j.config.PropertiesConfiguration.doConfigure(PropertiesConfiguration.java:127)
	at org.apache.log4j.config.Log4j1Configuration.initialize(Log4j1Configuration.java:59)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:295)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:621)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
```
changes to get CBMutationOutputFormatterTest running

CBMutationOutputFormatterTest is looking for specific log messages from
accumulo code.  It was not seeing those because there was no slf4j2
provider.  Configured a log4j2 slf4j2 provider to make everyone happy.

These changes plus changes in in memory accumulo that are not yet pushed
fix many tests that were failing.